export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const USER_FOODS_LOADING = 'USER_FOODS_LOADING';
export const USER_FOODS_FAILED = 'USER_FOODS_FAILED';
export const ADD_USER_FOODS = 'ADD_USER_FOODS';
export const ADD_USER_FOOD_ITEM = 'ADD_USER_FOOD_ITEM';
export const ADD_FOODS_TO_RENDER = 'ADD_FOODS_TO_RENDER';

export const FOODS_LOADING = 'FOODS_LOADING';
export const FOODS_FAILED = 'FOODS_FAILED';
export const ADD_FOODS = 'ADD_FOODS';
export const ADD_FOOD_ITEM = 'ADD_FOOD_ITEM';